# Generated by Django 5.1.7 on 2025-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='verification_documents',
        ),
        migrations.AddField(
            model_name='userverification',
            name='address_proof',
            field=models.FileField(null=True, upload_to='verification_documents/address/'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='id_document',
            field=models.FileField(null=True, upload_to='verification_documents/id/'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
