# Generated by Django 5.1.7 on 2025-11-22 09:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='address_proof',
            field=models.ImageField(help_text='Upload a JPEG or PNG image of your address proof', null=True, upload_to='verification_documents/address/', validators=[users.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='id_document',
            field=models.ImageField(help_text='Upload a JPEG or PNG image of your ID document', null=True, upload_to='verification_documents/id/', validators=[users.models.validate_image_file_extension]),
        ),
    ]
