# Generated by Django 5.1.7 on 2025-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Deadline for applications', null=True),
        ),
    ]
