# Generated by Django 5.1.7 on 2025-11-22 10:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_program_program_type_beneficiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed description of the program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='eligibility_criteria',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Who can apply and requirements'),
        ),
    ]
