# Generated by Django 5.1.7 on 2025-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='HEO Foundation', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('footer_text', models.TextField(default='Empowering dreams through education')),
                ('email', models.EmailField(default='info@heofoundation.org', max_length=254)),
                ('phone', models.CharField(default='+1 234 567 8900', max_length=20)),
                ('address', models.TextField(default='123 Education Street')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
