# Generated by Django 5.1.7 on 2025-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='address',
            new_name='contact_address',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='HEO Foundation provides educational opportunities and support to ambitious students worldwide.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Empowering Dreams Through Education', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', help_text='Hex color code', max_length=7),
        ),
    ]
