# Generated by Django 5.1.7 on 2025-03-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['order'], 'verbose_name': 'Hero Slider Image', 'verbose_name_plural': 'Slider Images'},
        ),
    ]
