# Generated by Django 5.1.7 on 2025-08-06 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_program_application_deadline_and_more'),
        ('core', '0008_sitesettings_about_subtitle_sitesettings_about_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Student's full name", max_length=200)),
                ('date_of_birth', models.DateField(help_text="Student's date of birth")),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text="Student or guardian's phone number", max_length=15)),
                ('email', models.EmailField(blank=True, help_text="Student or guardian's email", max_length=254)),
                ('school_name', models.CharField(help_text='Name of the school', max_length=300)),
                ('school_address', models.TextField(help_text="School's complete address")),
                ('current_class', models.CharField(choices=[('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('sss_1', 'SSS 1'), ('sss_2', 'SSS 2'), ('sss_3', 'SSS 3'), ('university_year_1', 'University Year 1'), ('university_year_2', 'University Year 2'), ('university_year_3', 'University Year 3'), ('university_year_4', 'University Year 4'), ('postgraduate', 'Postgraduate')], help_text='Current class/level', max_length=20)),
                ('scholarship_amount', models.DecimalField(decimal_places=2, help_text='Scholarship amount in Naira', max_digits=10)),
                ('scholarship_start_date', models.DateField(help_text='When the scholarship started')),
                ('scholarship_end_date', models.DateField(blank=True, help_text='When the scholarship ends (if applicable)', null=True)),
                ('scholarship_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('discontinued', 'Discontinued')], default='active', max_length=15)),
                ('guardian_name', models.CharField(help_text="Parent/Guardian's full name", max_length=200)),
                ('guardian_relationship', models.CharField(help_text='Relationship to student (e.g., Father, Mother, Uncle)', max_length=50)),
                ('guardian_phone', models.CharField(help_text="Guardian's phone number", max_length=15)),
                ('guardian_address', models.TextField(help_text="Guardian's address")),
                ('photo', models.ImageField(blank=True, help_text="Student's photo", null=True, upload_to='students/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who added this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='Associated scholarship program', null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.program')),
            ],
            options={
                'verbose_name': 'Scholarship Student',
                'verbose_name_plural': 'Scholarship Students',
                'ordering': ['full_name', 'school_name'],
            },
        ),
    ]
