# Generated by Django 5.1.7 on 2025-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='Allowed file types: JPEG, JPG, PNG, GIF, PDF. Maximum size: 10MB', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('image/jpeg', 'JPEG Image'), ('image/jpg', 'JPG Image'), ('image/png', 'PNG Image'), ('image/gif', 'GIF Image'), ('application/pdf', 'PDF Document')], help_text='Select the type of file you are uploading', max_length=50),
        ),
    ]
