# Generated by Django 5.1.7 on 2025-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_media_file_alter_media_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mime_type',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
