# Generated by Django 5.1.7 on 2025-11-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_media_file_size_remove_media_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
